### ISSUE TITLE
URL matching is matching too many domains

### ISSUE THREAD

**Issue by ContentPersonality2** [DarkThemeHub/GithubDarkTheme#136]
I'm using Stylus to apply this theme. By default this theme runs on too many sites, it runs on sites completely unreleated to GitHub due to the regex that is has set by default. I fixed this by manually changing [this](https://i.imgur.com/mRivOTT.png) to [this](https://i.imgur.com/vJEOepG.png)

**Comment by Snazzie** [comment]
Can you give example url's that you have come across that should not be themed?

**Comment by ContentPersonality2** [comment]
> 
> 
> Can you give example urls that you have come across that should not be themed?

Loads of sites, [https://www.userstyles.org](url) for one, it changes the header colour. I noticed loads of other sites too however I can't remember them specifically. My edit completely fixed the issues as I now tell it to only run on GitHub and no where else.

**Comment by Snazzie** [comment]
"Loads of sites" isnt helpful. i just checked https://www.userstyles.org  and its not applied there.

The regex as of now is quite effective. If the theme is being applied to places that shouldn't be, do note it down and post it in here, otherwise, i cant resolve it.

There are reasons for using regex solely to determine what sites should the theme be applied to.
E.g. compatibility with both stylus and upcoming dedicated extension and having one regex to match for all.

[tests for current regex](https://regex101.com/r/bW6cYw/3)

**Comment by atompkins** [comment]
URLs with github in the path are matching incorrectly
here are some examples
https://codeclimate.com/github/fallenswordhelper/fallenswordhelper
https://codebeat.co/projects/github-com-fallenswordhelper-fallenswordhelper-master
