### ISSUE TITLE
Repo nav header background is white

### ISSUE THREAD

**Issue by Snazzie** [DarkThemeHub/GithubDarkTheme#139]
**Describe the bug**
it seems like github added @media today to css which now enforces white on the background...

**Screenshots**
![image](https://user-images.githubusercontent.com/19627023/74072819-01455d80-4a00-11ea-9695-9588d560917b.png)

**Comment by yulayula16** [comment]
I was looking through your CSS and I have few suggestions here to change.

for your properties for the scrollbars on line 5032

```
:root {
    scrollbar-color: rgba(175, 175, 175, 0.5) #1d1d1d !important;
    scrollbar-width: thin !important;
```

change it to `::-webkit-scrollbar` for better compatibility across browsers.

```
:root {
    ::-webkit-scrollbar: rgba(175, 175, 175, 0.5) #1d1d1d !important;
    ::-webkit-scrollbar-width: thin !important;
``` 

and fix for shorthand for `background` after declaring `background-color` on line 7866

```
/* Github dropdown menu */
.select-menu-item,
.select-menu-list,
.SelectMenu-item,
.SelectMenu-list,
.SelectMenu-divider {
    background-color: unset !important;
    background: none !important;
}
```
remove line for `background: none !important;` since you already specified `background-color` property.

and lastly remove the duplicate property name for the font name `Menlo` on line 83 since it was already labelled in the first part, you added it twice after `"Liberation Mono"`

```
font-family: "Menlo", Consolas, "Liberation Mono", Courier, monospace !important;
```

**Comment by Snazzie** [comment]
@yulayula16 Great! Can you move this into its own issue? :)
