### ISSUE TITLE
Navbar in small views

### ISSUE THREAD

**Issue by Akianonymus** [DarkThemeHub/GithubDarkTheme#149]
The grey colour pallete on the navbar looks kinda weird, i am using the theme in an android browser, [Yuzu browser](https://github.com/hazuki0x0/YuzuBrowser).
I don't know if mobile views are the scope of this theme....

The solution i think would work is to use dark grey on navbar, matching the current colour of rest of the page and change active navbar to current inactive navbar colour( or a little more dark than that ).

Here is the a screenshot of how it looks:

![Screenshot_20200404-100649](https://user-images.githubusercontent.com/32216346/78418854-c78a7f00-765d-11ea-84e6-9d3086794c6a.png)

Also, can you point out what refers to the inactive navbar colour in the css ? Would be a great help.

Anyway, this is by far the best consistent dark theme i have found, thank you for that.

**Comment by Snazzie** [comment]
On mobile, it does look a little out of place, but i think its because of the slider. When the slider isnt there, it looks quite normal. I think the background colour could stay the same but active colour can be lighter. 

Not entirely sure what i want to do really, is there a reason you're not using github android app? it has a native dark theme :P 
https://play.google.com/store/apps/details?id=com.github.android&hl=en 

![image](https://user-images.githubusercontent.com/19627023/78579702-3bc54e00-7829-11ea-81cf-c649ad33ddc4.png)


> Anyway, this is by far the best consistent dark theme i have found, thank you for that.

Thanks, i was annoyed that there wasnt a properly maintained darktheme for github, so i took a broken one, fixed it up and continued to support it. 

I think github will likely drop their own native desktop dark theme this year. Which hopefully would redirect this work to different styles instead of just keeping it broken free.
I was planning on introducing different pallets that users can create and share.

Was hoping to get some people on board (not going so well) to increase motivation and start theming other sites. ( was thinking, Azure and AWS ) Maybe you can drop some suggestions on what you'd like to have.
